const STOP=new Set('de la el los las un una unos unas y o que en por para con del al a es son se como cómo cual cuál cuales qué que do da dos das um uma e ou em para com é são se como qual quais o a os as the a an and or of to in is are what how which'.split(' '));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const tokens=s=>[...new Set(norm(s).match(/[a-z0-9áéíóúñü]+/g)||[])].filter(x=>x.length>2&&!STOP.has(x));
function score(q,c){const hay=norm(c.title+' '+c.text),qs=tokens(q);let n=0;for(const t of qs){if(hay.includes(t))n+=t.length>7?4:2}const phrase=norm(q).trim();if(phrase.length>5&&hay.includes(phrase))n+=12;return n}
export async function onRequestPost(context){try{const ip=context.request.headers.get('CF-Connecting-IP')||'unknown';const body=await context.request.json();const message=String(body.message||'').trim();if(!message||message.length>600)return Response.json({error:'Pregunta inválida.'},{status:400});if(!context.env.OPENAI_API_KEY)return Response.json({error:'OPENAI_API_KEY no está configurada.'},{status:500});
const idxRes=await context.env.ASSETS.fetch(new URL('/data/ai-index.json',context.request.url));if(!idxRes.ok)throw new Error('No index');const idx=await idxRes.json();const ranked=idx.map(x=>[score(message,x),x]).filter(x=>x[0]>0).sort((a,b)=>b[0]-a[0]).slice(0,8).map(x=>x[1]);const contextText=ranked.map((x,i)=>`[FUENTE ${i+1}] ${x.title}\nURL: ${x.url}\n${x.text}`).join('\n\n');const hist=Array.isArray(body.history)?body.history.slice(-6).filter(x=>x&&['user','assistant'].includes(x.role)&&typeof x.content==='string').map(x=>({role:x.role,content:x.content.slice(0,900)})):[];
const system=`Eres el asistente de PKA No Oficial Wiki, una wiki comunitaria sobre PokeAlliance. Responde SIEMPRE en el mismo idioma que use el usuario en su mensaje actual. Usa únicamente la información incluida en CONTEXTO DE LA WIKI. No uses conocimiento general de Pokémon para completar huecos. Si el contexto no contiene la respuesta, dilo claramente y sugiere qué página relacionada consultar si existe. Sé concreto pero útil. No inventes estadísticas, ubicaciones, tiers, mecánicas ni nombres. No afirmes que una fuente dice algo que no aparece en el contexto. Las fuentes clicables se muestran por separado, así que no inventes URLs en el texto.`;
const payload={model:context.env.OPENAI_MODEL||'gpt-5-mini',input:[{role:'system',content:system},...hist,{role:'user',content:`CONTEXTO DE LA WIKI:\n${contextText||'(No se encontraron fragmentos relevantes)'}\n\nPREGUNTA:\n${message}`}],max_output_tokens:650};const ai=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Authorization':`Bearer ${context.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await ai.json();if(!ai.ok){console.log('OpenAI error',data?.error?.message||ai.status);return Response.json({error:'No se pudo obtener respuesta de la IA.'},{status:502})}let answer=data.output_text;if(!answer&&Array.isArray(data.output))answer=data.output.flatMap(o=>o.content||[]).filter(c=>c.type==='output_text').map(c=>c.text).join('\n');answer=String(answer||'No encontré una respuesta en la información disponible.').trim();const seen=new Set(),sources=ranked.slice(0,4).filter(x=>!seen.has(x.url)&&seen.add(x.url)).map(x=>({title:x.title,url:x.url}));return Response.json({answer,sources},{headers:{'Cache-Control':'no-store'}})}catch(e){console.log(e);return Response.json({error:'Error interno del asistente.'},{status:500})}}
export async function onRequestGet(){return Response.json({ok:true,service:'PKA Wiki AI'})}
