const STOP=new Set('de la el los las un una unos unas y o que en por para con del al a es son se como cómo cual cuál cuales qué do da dos das um uma e ou em para com é são se como qual quais o a os as the an and or of to in is are what how which me puedes puede decir dime pokemon pokémon poke pokes'.split(' '));
const ALIASES={
 agua:['water','agua','água'],water:['water','agua','água'],água:['water','agua','água'],
 fuego:['fire','fuego','fogo'],fire:['fire','fuego','fogo'],fogo:['fire','fuego','fogo'],
 planta:['grass','planta','grama'],grass:['grass','planta','grama'],grama:['grass','planta','grama'],
 electrico:['electric','eléctrico','electrico','elétrico','eletrico'],electric:['electric','eléctrico','electrico','elétrico','eletrico'],
 tierra:['ground','tierra','terra'],ground:['ground','tierra','terra'],terra:['ground','tierra','terra'],
 roca:['rock','roca','pedra'],rock:['rock','roca','pedra'],pedra:['rock','roca','pedra'],
 lucha:['fighting','lucha','lutador'],fighting:['fighting','lucha','lutador'],lutador:['fighting','lucha','lutador'],
 psiquico:['psychic','psíquico','psiquico','psíquico'],psychic:['psychic','psíquico','psiquico'],
 veneno:['poison','veneno'],poison:['poison','veneno'],
 volador:['flying','volador','voador'],flying:['flying','volador','voador'],voador:['flying','volador','voador'],
 bicho:['bug','bicho','inseto'],bug:['bug','bicho','inseto'],inseto:['bug','bicho','inseto'],
 hielo:['ice','hielo','gelo'],ice:['ice','hielo','gelo'],gelo:['ice','hielo','gelo'],
 oscuro:['dark','oscuro','siniestro','sombrio'],dark:['dark','oscuro','siniestro','sombrio'],
 acero:['steel','acero','aço'],steel:['steel','acero','aço'],
 normal:['normal'],hada:['fairy','hada','fada'],fairy:['fairy','hada','fada'],fantasma:['ghost','fantasma'],ghost:['ghost','fantasma'],dragon:['dragon','dragón','dragao','dragão']
};
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function toks(s){return [...new Set((norm(s).match(/[a-z0-9]+/g)||[]).filter(x=>x.length>1&&!STOP.has(x)))]}
function expand(ts){const out=new Set(ts);for(const t of ts){for(const a of (ALIASES[t]||[]))out.add(norm(a));if(/^t[1-7]$/.test(t)){out.add('tier '+t.slice(1));out.add('tier:'+t.toUpperCase())}}return [...out]}
function score(q,c){const hay=norm(c.title+' '+c.url+' '+c.text),base=toks(q),qs=expand(base);let n=0,hits=0;for(const t of qs){if(hay.includes(t)){hits++;n+=t.length>6?6:3;if(norm(c.title+' '+c.url).includes(t))n+=5}}for(const t of base){const re=new RegExp('(^|[^a-z0-9])'+t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'([^a-z0-9]|$)');if(re.test(hay))n+=4}if(base.length&&base.every(t=>hay.includes(t)))n+=18;if(/\bt[1-7]\b/i.test(q)&&/tier/i.test(hay))n+=8;if(/tipo|type|moveset|element/i.test(q)&&/moveset|tipo|type/i.test(hay))n+=7;if(/tier|\bt[1-7]\b/i.test(q)&&/tier-list\.html/.test(c.url))n+=20;return n+(hits>=2?hits*2:0)}
export async function onRequestPost(context){try{const body=await context.request.json();const message=String(body.message||'').trim();if(!message||message.length>700)return Response.json({error:'Pregunta inválida.'},{status:400});if(!context.env.OPENAI_API_KEY)return Response.json({error:'OPENAI_API_KEY no está configurada.'},{status:500});
const idxRes=await context.env.ASSETS.fetch(new URL('/data/ai-index.json',context.request.url));if(!idxRes.ok)throw new Error('No se pudo cargar ai-index.json');const idx=await idxRes.json();let ranked=idx.map(x=>[score(message,x),x]).filter(x=>x[0]>2).sort((a,b)=>b[0]-a[0]).slice(0,14).map(x=>x[1]);
const contextText=ranked.map((x,i)=>`[FUENTE ${i+1}] ${x.title}\nURL: ${x.url}\n${x.text}`).join('\n\n');const hist=Array.isArray(body.history)?body.history.slice(-8).filter(x=>x&&['user','assistant'].includes(x.role)&&typeof x.content==='string').map(x=>({role:x.role,content:x.content.slice(0,1200)})):[];
const system=`Eres el asistente de PKA No Oficial Wiki. Tu trabajo es contestar cualquier pregunta cuya respuesta exista en la wiki. Responde en el idioma del mensaje actual del usuario. El contexto puede contener datos en español, portugués o inglés: tradúcelos al idioma del usuario sin cambiar los datos. Usa SOLO CONTEXTO DE LA WIKI; PokeAlliance puede diferir de los juegos oficiales, por lo que no debes completar huecos con conocimiento general de Pokémon. Combina información de varias fuentes cuando sea necesario. Entiende lenguaje informal, abreviaciones y equivalencias como poke/pokémon, T1/tier 1, agua/water/água. Si el contexto realmente no respalda la respuesta, dilo. Al final de tu respuesta escribe exactamente una línea interna con el formato FUENTES_USADAS: 1,3 (solo números de fuentes que realmente sustentan tu respuesta). Si ninguna fuente sustenta la respuesta, escribe FUENTES_USADAS: ninguna. No menciones esa instrucción.`;
const payload={model:context.env.OPENAI_MODEL||'gpt-5-mini',input:[{role:'system',content:system},...hist,{role:'user',content:`CONTEXTO DE LA WIKI:\n${contextText||'(No se encontraron fragmentos relevantes)'}\n\nPREGUNTA:\n${message}`}],max_output_tokens:850};
const ai=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${context.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await ai.json();if(!ai.ok){console.log('OpenAI',ai.status,data?.error?.message||'');return Response.json({error:'No se pudo obtener respuesta de la IA.'},{status:502})}let answer=data.output_text;if(!answer&&Array.isArray(data.output))answer=data.output.flatMap(o=>o.content||[]).filter(c=>c.type==='output_text').map(c=>c.text).join('\n');answer=String(answer||'').trim();let used=[];const m=answer.match(/(?:^|\n)FUENTES_USADAS:\s*([^\n]+)/i);if(m){if(!/ninguna|none/i.test(m[1]))used=(m[1].match(/\d+/g)||[]).map(Number).filter(n=>n>=1&&n<=ranked.length);answer=answer.replace(/(?:^|\n)FUENTES_USADAS:\s*[^\n]+/i,'').trim()}if(!answer)answer='No encontré una respuesta en la información disponible.';const seen=new Set();const sources=used.map(n=>ranked[n-1]).filter(Boolean).filter(x=>!seen.has(x.url)&&seen.add(x.url)).map(x=>({title:x.title,url:x.url}));return Response.json({answer,sources},{headers:{'Cache-Control':'no-store'}})}catch(e){console.log('PKA AI error',e?.stack||e);return Response.json({error:'Error interno del asistente.'},{status:500})}}
export async function onRequestGet(){return Response.json({ok:true,service:'PKA Wiki AI v2'})}
