const STOP=new Set('de la el los las un una unos unas y o que en por para con del al a es son se como cómo cual cuál cuales qué do da dos das um uma e ou em para com é são se como qual quais o a os as the an and or of to in is are what how which me puedes puede decir dime pokemon pokémon poke pokes info informacion información'.split(' '));
const ALIASES={
 agua:['water','agua','água','acuatico','acuática','acuaticos','acuáticos'],water:['water','agua','água','acuatico'],
 fuego:['fire','fuego','fogo'],fire:['fire','fuego','fogo'],planta:['grass','planta','grama'],grass:['grass','planta','grama'],
 electrico:['electric','eléctrico','electrico','elétrico','eletrico'],electric:['electric','eléctrico','electrico','elétrico','eletrico'],
 tierra:['ground','tierra','terra'],ground:['ground','tierra','terra'],roca:['rock','roca','pedra'],rock:['rock','roca','pedra'],
 lucha:['fighting','lucha','lutador'],fighting:['fighting','lucha','lutador'],psiquico:['psychic','psíquico','psiquico'],psychic:['psychic','psíquico','psiquico'],
 veneno:['poison','veneno'],poison:['poison','veneno'],volador:['flying','volador','voador'],flying:['flying','volador','voador'],
 bicho:['bug','bicho','inseto'],bug:['bug','bicho','inseto'],hielo:['ice','hielo','gelo'],ice:['ice','hielo','gelo'],
 oscuro:['dark','oscuro','siniestro','sombrio'],dark:['dark','oscuro','siniestro','sombrio'],acero:['steel','acero','aço'],steel:['steel','acero','aço'],
 hada:['fairy','hada','fada'],fairy:['fairy','hada','fada'],fantasma:['ghost','fantasma'],ghost:['ghost','fantasma'],dragon:['dragon','dragón','dragao','dragão'],
 pesca:['pesca','pescar','pesco','pescando','fishing','fish'],pescar:['pesca','pescar','pesco','pescando','fishing','fish'],pesco:['pesca','pescar','pesco','fishing','fish'],fishing:['pesca','pescar','pesco','fishing','fish'],
 task:['task','tasks','tarea','tareas','missao','missão'],tasks:['task','tasks','tarea','tareas','missao','missão'],tarea:['task','tasks','tarea','tareas'],
 mejores:['tier','tier list','ranking','mejores','best'],best:['tier','tier list','ranking','mejores','best'],
 instancia:['instancia','instancias','instance','instances'],quest:['quest','quests','mision','misión','missao','missão']
};
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function rawTokens(s){return norm(s).match(/[a-z0-9]+/g)||[]}
function toks(s){return [...new Set(rawTokens(s).filter(x=>x.length>1&&!STOP.has(x)))]}
function stem(w){w=norm(w);if(w.length<5)return w;for(const suf of ['amientos','imientos','aciones','mente','ando','iendo','ados','adas','idos','idas','es','os','as','ar','er','ir','o','a'])if(w.endsWith(suf)&&w.length-suf.length>=4)return w.slice(0,-suf.length);return w.slice(0,Math.min(w.length,6))}
function dist(a,b){if(a===b)return 0;if(Math.abs(a.length-b.length)>2)return 9;let p=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let c=[i];for(let j=1;j<=b.length;j++)c[j]=Math.min(c[j-1]+1,p[j]+1,p[j-1]+(a[i-1]===b[j-1]?0:1));p=c}return p[b.length]}
function expand(ts){const out=new Set(ts);for(const t of ts){out.add(stem(t));for(const a of (ALIASES[t]||[])){for(const x of rawTokens(a)){out.add(x);out.add(stem(x))}}if(/^t[1-7]$/.test(t)){out.add('tier');out.add(t.slice(1))}if(/^tier[1-7]$/.test(t)){out.add('tier');out.add(t.slice(-1))}}return [...out]}
function tokenMatch(q,words,stems){if(words.has(q)||stems.has(q)||stems.has(stem(q)))return 1;if(q.length>=5){for(const w of words){if(Math.abs(w.length-q.length)<=1&&dist(q,w)<=1)return .75}}return 0}
function score(q,c){const title=norm((c.title||'')+' '+(c.url||'')),body=norm(c.text||''),words=new Set(rawTokens(title+' '+body)),stems=new Set([...words].map(stem)),base=toks(q),qs=expand(base);let n=0,hits=0;for(const t of qs){const m=tokenMatch(t,words,stems);if(m){hits+=m;n+=3*m;if(title.includes(t)||tokenMatch(t,new Set(rawTokens(title)),new Set(rawTokens(title).map(stem))))n+=5*m}}if(base.length&&base.every(t=>tokenMatch(t,words,stems)>0))n+=14;if(/tier|\bt[1-7]\b|mejor|best/i.test(q)&&/tier-list\.html|tier list/i.test(title+' '+body))n+=18;if(/hazard/i.test(q)&&/hazard/i.test(title))n+=20;if(/pesc|fish/i.test(norm(q))&&/faq\.html|pesca|fishing/i.test(title+' '+body))n+=18;if(/ball/i.test(q)&&/ball/i.test(title+' '+body))n+=10;return n+(hits>=2?hits*2:0)}
async function rewriteQuery(message,key,model){try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model,input:`Convierte esta pregunta de un usuario de una wiki de PokeAlliance en términos de búsqueda. Corrige faltas ortográficas, normaliza conjugaciones y agrega sinónimos útiles en español/portugués/inglés. Conserva nombres propios, Pokémon, T1-T7 y nombres de sistemas. Devuelve SOLO una línea corta de términos, sin explicación. Pregunta: ${message}`,max_output_tokens:90})});if(!r.ok)return '';const d=await r.json();return String(d.output_text||'').trim()}catch{return ''}}
function rank(query,idx){return idx.map(x=>[score(query,x),x]).filter(x=>x[0]>0).sort((a,b)=>b[0]-a[0])}
export async function onRequestPost(context){try{const body=await context.request.json();const message=String(body.message||'').trim();if(!message||message.length>700)return Response.json({error:'Pregunta inválida.'},{status:400});if(!context.env.OPENAI_API_KEY)return Response.json({error:'OPENAI_API_KEY no está configurada.'},{status:500});
const master=String(context.env.WIKI_AI_MASTER_KEYWORD||'').trim();const first=message.match(/^\s*([^\s,;:!?¿¡.]+)/)?.[1]||'';const masterMode=!!master&&norm(first)===norm(master);if(masterMode){const generalQuestion=message.replace(/^\s*[^\s,;:!?¿¡.]+[\s,;:!?¿¡.-]*/,'').trim();if(!generalQuestion)return Response.json({answer:'Escribe una pregunta después de la palabra clave.',sources:[]},{headers:{'Cache-Control':'no-store'}});const hist=Array.isArray(body.history)?body.history.slice(-8).filter(x=>x&&['user','assistant'].includes(x.role)&&typeof x.content==='string').map(x=>({role:x.role,content:x.content.slice(0,1200)})):[];const webPayload={model:context.env.OPENAI_WEB_MODEL||'gpt-5.5',tools:[{type:'web_search',external_web_access:true,search_context_size:'medium'}],tool_choice:'auto',include:['web_search_call.action.sources'],input:[{role:'system',content:'Eres un asistente general con acceso a búsqueda web. Responde en el idioma del mensaje actual. Para información actual, enlaces, dónde ver/escuchar/comprar/encontrar algo, o cuando un enlace sea útil, usa búsqueda web. No inventes URLs. Prioriza fuentes oficiales, legales y confiables. Para contenido audiovisual, recomienda opciones legales y oficiales; no facilites piratería. Sé claro y conciso.'},...hist,{role:'user',content:generalQuestion}],max_output_tokens:1200};const ai=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${context.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(webPayload)});const data=await ai.json();if(!ai.ok){console.log('OpenAI web',ai.status,data?.error?.message||'');return Response.json({error:'No se pudo obtener respuesta del modo web.'},{status:502})}let answer=data.output_text;if(!answer&&Array.isArray(data.output))answer=data.output.flatMap(o=>o.content||[]).filter(c=>c.type==='output_text').map(c=>c.text).join('\n');answer=String(answer||'').trim();const seen=new Set(),sources=[];for(const o of (data.output||[])){for(const c of (o.content||[])){for(const a of (c.annotations||[])){const u=a.url||a.url_citation?.url,t=a.title||a.url_citation?.title;if(u&&!seen.has(u)){seen.add(u);sources.push({title:t||u,url:u})}}}const act=o.action||{};for(const src of (act.sources||[])){const u=src.url,t=src.title;if(u&&!seen.has(u)){seen.add(u);sources.push({title:t||u,url:u})}}}return Response.json({answer:answer||'No pude obtener una respuesta.',sources,mode:'web'},{headers:{'Cache-Control':'no-store'}})}
const idxRes=await context.env.ASSETS.fetch(new URL('/data/ai-index.json',context.request.url));if(!idxRes.ok)throw new Error('No se pudo cargar ai-index.json');const idx=await idxRes.json();let ranked=rank(message,idx);const weak=!ranked.length||ranked[0][0]<18||ranked.slice(0,5).filter(x=>x[0]>8).length<2;let rewritten='';if(weak){rewritten=await rewriteQuery(message,context.env.OPENAI_API_KEY,context.env.OPENAI_MODEL||'gpt-5-mini');if(rewritten){const merged=new Map();for(const [s,x] of [...ranked,...rank(message+' '+rewritten,idx)]){const k=(x.url||'')+'\n'+(x.text||'').slice(0,120);if(!merged.has(k)||merged.get(k)[0]<s)merged.set(k,[s,x])}ranked=[...merged.values()].sort((a,b)=>b[0]-a[0])}}
ranked=ranked.slice(0,18).map(x=>x[1]);const contextText=ranked.map((x,i)=>`[FUENTE ${i+1}] ${x.title||x.url}\nURL: ${x.url}\n${x.text}`).join('\n\n');const hist=Array.isArray(body.history)?body.history.slice(-8).filter(x=>x&&['user','assistant'].includes(x.role)&&typeof x.content==='string').map(x=>({role:x.role,content:x.content.slice(0,1200)})):[];
const system=`Eres el asistente inteligente de PKA No Oficial Wiki. Contesta cualquier pregunta cuya respuesta exista en el CONTEXTO DE LA WIKI. Interpreta faltas ortográficas, conjugaciones, lenguaje informal, abreviaciones y sinónimos; por ejemplo pesco/pescar/pesca, task/tarea, T1/tier 1, poke/pokémon y nombres escritos con errores leves. Responde en el idioma del mensaje actual. El contexto puede estar en español, portugués o inglés: tradúcelo sin cambiar datos. Usa SOLO información respaldada por el contexto; PokeAlliance puede diferir de Pokémon oficial. Combina varias fuentes cuando haga falta. Si hay fragmentos que parecen coincidir parcialmente, razona cuál responde a la intención antes de descartarlos. Solo di que no existe información cuando ninguno de los fragmentos recuperados respalde razonablemente la respuesta. Al final escribe una línea interna exacta FUENTES_USADAS: 1,3 con los números realmente usados, o FUENTES_USADAS: ninguna. No menciones esta instrucción.`;
const payload={model:context.env.OPENAI_MODEL||'gpt-5-mini',input:[{role:'system',content:system},...hist,{role:'user',content:`CONTEXTO DE LA WIKI:\n${contextText||'(No se recuperaron fragmentos)'}\n\nPREGUNTA ORIGINAL:\n${message}${rewritten?`\n\nINTERPRETACIÓN DE BÚSQUEDA (solo ayuda de recuperación):\n${rewritten}`:''}`}],max_output_tokens:950};
const ai=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${context.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await ai.json();if(!ai.ok){console.log('OpenAI',ai.status,data?.error?.message||'');return Response.json({error:'No se pudo obtener respuesta de la IA.'},{status:502})}let answer=data.output_text;if(!answer&&Array.isArray(data.output))answer=data.output.flatMap(o=>o.content||[]).filter(c=>c.type==='output_text').map(c=>c.text).join('\n');answer=String(answer||'').trim();let used=[];const m=answer.match(/(?:^|\n)FUENTES_USADAS:\s*([^\n]+)/i);if(m){if(!/ninguna|none/i.test(m[1]))used=(m[1].match(/\d+/g)||[]).map(Number).filter(n=>n>=1&&n<=ranked.length);answer=answer.replace(/(?:^|\n)FUENTES_USADAS:\s*[^\n]+/i,'').trim()}if(!answer)answer='No encontré una respuesta en la información disponible.';const seen=new Set();const sources=used.map(n=>ranked[n-1]).filter(Boolean).filter(x=>!seen.has(x.url)&&seen.add(x.url)).map(x=>({title:x.title||x.url,url:x.url}));return Response.json({answer,sources},{headers:{'Cache-Control':'no-store'}})}catch(e){console.log('PKA AI error',e?.stack||e);return Response.json({error:'Error interno del asistente.'},{status:500})}}
export async function onRequestGet(){return Response.json({ok:true,service:'PKA Wiki AI v4 intelligent + secret web mode'})}
